In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from sklearn.preprocessing import LabelEncoder

warnings.filterwarnings('ignore')

plt.style.use('seaborn-v0_8-whitegrid')
sns.set_palette('husl')

print ("✅ Librairies importées avec succès")
print (f"Pandas : {pd.__version__}")
print (f"Numpy : {pd.__version__}")

✅ Librairies importées avec succès
Pandas : 3.0.3
Numpy : 3.0.3

In [3]:
X = pd.read_csv('/Users/thierrymanuelzibiondobo/credit_scoring_project/data/processed/X_preprocessed.csv')
y = pd.read_csv('/Users/thierrymanuelzibiondobo/credit_scoring_project/data/processed/y_preprocessed.csv')

In [4]:
df = pd.read_csv('/Users/thierrymanuelzibiondobo/credit_scoring_project/data/raw/application_train.csv')

print(f"✅ Dataset chargé")
print(f"Dimensions : {df.shape[0]:,} lignes × {df.shape[1]} colonnes")

✅ Dataset chargé
Dimensions : 307,511 lignes × 122 colonnes

In [5]:
df['DEBT_INCOME_RATIO'] = df['AMT_CREDIT'] / df['AMT_INCOME_TOTAL']
df['ANNUITY_INCOME_RATIO'] = df['AMT_ANNUITY'] / df['AMT_INCOME_TOTAL']
df['CREDIT_GOODS_RATIO'] = df['AMT_ANNUITY'] / df['AMT_GOODS_PRICE']
df['AGE_YEARS'] = df['DAYS_BIRTH'] / -365
df['YEARS_EMPLOYED'] = df['DAYS_EMPLOYED'] / -365

In [6]:
#Vérification des valeurs

df[['DEBT_INCOME_RATIO', 'ANNUITY_INCOME_RATIO', 'CREDIT_GOODS_RATIO', 'AGE_YEARS', 'YEARS_EMPLOYED']].describe()

,DEBT_INCOME_RATIO,ANNUITY_INCOME_RATIO,CREDIT_GOODS_RATIO,AGE_YEARS,YEARS_EMPLOYED
count,307511.000000,307499.000000,307221.000000,307511.000000,307511.000000
mean,3.957570,0.180930,0.059919,43.936973,-174.835742
std,2.689728,0.094574,0.024655,11.956133,387.056895
min,0.004808,0.000224,0.007500,20.517808,-1000.665753
25%,2.018667,0.114782,0.042310,34.008219,0.791781
50%,3.265067,0.162833,0.051380,43.150685,3.323288
75%,5.159880,0.229067,0.072120,53.923288,7.561644
max,84.736842,1.875965,0.300000,69.120548,49.073973

In [7]:
df['YEARS_EMPLOYED'] = df['YEARS_EMPLOYED'].replace(df[df['YEARS_EMPLOYED'] < 0]['YEARS_EMPLOYED'].unique(), np.nan)

print(df['YEARS_EMPLOYED'].describe())

count    252137.000000
mean          6.531971
std           6.406466
min          -0.000000
25%           2.101370
50%           4.515068
75%           8.698630
max          49.073973
Name: YEARS_EMPLOYED, dtype: float64

In [9]:
df['CREDIT_TERM'] = df['AMT_CREDIT'] / df['AMT_ANNUITY']
df['INCOME_PER_PERSON'] = df['AMT_INCOME_TOTAL'] / df['CNT_FAM_MEMBERS']
df['EXT_SOURCE_MEAN'] = df[['EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3']].mean(axis=1)

In [10]:
df[['CREDIT_TERM', 'INCOME_PER_PERSON', 'EXT_SOURCE_MEAN']].describe()

         CREDIT_TERM  INCOME_PER_PERSON  EXT_SOURCE_MEAN
count  307499.000000       3.075090e+05    307339.000000
mean       21.612322       9.310588e+04         0.509251
std         7.823823       1.013734e+05         0.149802
min         8.036674       2.812500e+03         0.000006
25%        15.614496       4.725000e+04         0.413648
50%        20.000000       7.500000e+04         0.524502
75%        27.099985       1.125000e+05         0.622819
max        45.305079       3.900000e+07         0.878903

In [12]:
import os

df_features = df.copy()

processed_dir = os.path.join(os.path.expanduser('~'),
                             'credit_scoring_project',
                             'data', 'processed')

df_features.to_csv(os.path.join(processed_dir,
                                'application_features.csv'), index=False)

print(f"✅Dataset enrichi sauvegardé")
print(f"Dimensions : {df_features.shape}")
print(f"Nouvelles features créées : DEBT_INCOME_RATIO, ANNUITY_INCOME_RATIO,")
print(f"CREDIT_GOODS_RATIO, AGE_YEARS, YEARS_EMPLOYED, CREDIT_TERM,")
print(f"INCOME_PER_PERSON, EXT_SOURCE_MEAN")

✅Dataset enrichi sauvegardé
Dimensions : (307511, 130)
Nouvelles features créées : DEBT_INCOME_RATIO, ANNUITY_INCOME_RATIO,
CREDIT_GOODS_RATIO, AGE_YEARS, YEARS_EMPLOYED, CREDIT_TERM,
INCOME_PER_PERSON, EXT_SOURCE_MEAN